//! The UI map: every automation element of the FilmCraft window and every menu-bar command, with
//! where it lives (`panel`), how to make it visible from a fresh start (`reach`), what a click does
//! (`effect`) and the engine command behind it (`command`). The UI crawler
//! (`crates/ui-egui/tests/ui_map_crawl.rs`) writes `docs/ui-map.json`; it is embedded here so the
//! MCP server (and the bundled CLI) answer `ui_map` offline, in both modes.

use std::sync::OnceLock;

use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{Value, json};

/// `docs/ui-map.json` as generated by the crawler.
pub const MAP_JSON: &str = include_str!("../../../docs/ui-map.json");

/// Entries returned when the call names no `limit`.
pub const DEFAULT_LIMIT: usize = 40;
/// The most entries one call returns.
pub const MAX_LIMIT: usize = 500;

/// How to use an entry (returned with every answer).
pub const HOW: &str = "Entry with a `command`: run it with command_run (faster; works headless; in bridge mode a menu command that \
    has a dialog opens it, as the menu does). Otherwise follow `reach` from a fresh start (`ui.panel.show P` → ui_control \
    {method: \"ui.panel.show\", params: {panel: P}}; `ui.set mode=M` → ui_control {method: \"ui.set\", params: {mode: M}}; \
    `ui.menu.invoke C` / `command_run C {…}` → command_run; `ui.click ID` → ui_click), then ui_click the entry's id. \
    `{clip}`, `{item}`, `{track}`, `{name}`… stand for one element of a family: take the real id from ui_elements \
    (prefix = the id up to the brace). `close` says how to dismiss what the element opens; kind `field` / `number` takes \
    ui_type after the click; kind `slider` / `handle` takes ui_drag.";

#[derive(Debug, Default, Deserialize, JsonSchema)]
pub struct UiMapParams {
    /// Only entries whose id starts with this, e.g. `timeline.track.`, `export.video.`, `addTracks.`.
    #[serde(default)]
    pub prefix: Option<String>,
    /// Only entries in this panel, dialog, mode or menu (case-insensitive, part of the name is enough): `Timeline`,
    /// `Effect Controls`, `Export mode`, `Dialog: Add Tracks`, `Menu: Sequence`, `Header`.
    #[serde(default)]
    pub panel: Option<String>,
    /// Only this kind: button, toggle, checkbox, dropdown, option, menu, menu-item, tab, field, number, slider, handle, area, link.
    #[serde(default)]
    pub kind: Option<String>,
    /// Words to look for in the id, label, effect, command and panel (all must match, any order), e.g.
    /// `add tracks`, `razor`, `mute`, `export preset`.
    #[serde(default)]
    pub query: Option<String>,
    /// How many entries to return (default 40, at most 500).
    #[serde(default)]
    pub limit: Option<usize>,
    /// Skip this many matches first (to page through a long answer).
    #[serde(default)]
    pub offset: Option<usize>,
}

/// The parsed map (parsed once).
pub fn map() -> Result<&'static Value, String> {
    static MAP: OnceLock<Result<Value, String>> = OnceLock::new();
    MAP.get_or_init(|| serde_json::from_str(MAP_JSON).map_err(|e| format!("the embedded UI map is unreadable: {e}"))).as_ref().map_err(Clone::clone)
}

fn text<'a>(e: &'a Value, k: &str) -> &'a str {
    e.get(k).and_then(Value::as_str).unwrap_or("")
}

/// How well `e` answers `words` (`None`: some word is missing). Every word must occur in the id,
/// label, effect, command, panel or an example id; hits in the id, label and command count most.
fn score(e: &Value, words: &[String], query: &str) -> Option<u32> {
    if words.is_empty() {
        return Some(0);
    }
    let id = text(e, "id").to_lowercase();
    let label = text(e, "label").to_lowercase();
    let command = text(e, "command").to_lowercase();
    let panel = text(e, "panel").to_lowercase();
    let effect = text(e, "effect").to_lowercase();
    let examples = e
        .get("examples")
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect::<Vec<_>>().join(" ").to_lowercase())
        .unwrap_or_default();
    // `addTracks` matches `add tracks`
    let squash = |s: &str| s.replace([' ', '-', '_'], "");
    let mut total = 0u32;
    for w in words {
        let mut s = 0u32;
        if id.contains(w.as_str()) {
            s += 4;
        }
        if label.contains(w.as_str()) {
            s += 4;
        }
        if command.contains(w.as_str()) {
            s += 3;
        }
        if panel.contains(w.as_str()) {
            s += 1;
        }
        if effect.contains(w.as_str()) || examples.contains(w.as_str()) {
            s += 1;
        }
        if s == 0 {
            return None;
        }
        total = total.saturating_add(s);
    }
    let q = query.to_lowercase();
    if id == q || command == q {
        total = total.saturating_add(100);
    } else if label == q || squash(&label) == squash(&q) || id.ends_with(&squash(&q)) {
        total = total.saturating_add(40);
    }
    Some(total)
}

/// The entries matching `p`, best first (ties in id order), with paging.
pub fn search(p: &UiMapParams) -> Result<Value, String> {
    let m = map()?;
    let els = m.get("elements").and_then(Value::as_array).ok_or("the embedded UI map lists no elements")?;
    let prefix = p.prefix.as_deref().unwrap_or("");
    let panel = p.panel.as_deref().map(|s| s.trim().to_lowercase()).filter(|s| !s.is_empty());
    let kind = p.kind.as_deref().map(|s| s.trim().to_lowercase()).filter(|s| !s.is_empty());
    let query = p.query.as_deref().unwrap_or("").trim();
    let words: Vec<String> = query.to_lowercase().split_whitespace().map(str::to_string).collect();
    let mut hits: Vec<(u32, &Value)> = Vec::new();
    for e in els {
        if !text(e, "id").starts_with(prefix) {
            continue;
        }
        if panel.as_deref().is_some_and(|pn| !text(e, "panel").to_lowercase().contains(pn)) {
            continue;
        }
        if kind.as_deref().is_some_and(|k| text(e, "kind") != k) {
            continue;
        }
        if let Some(s) = score(e, &words, query) {
            hits.push((s, e));
        }
    }
    // stable: equal scores keep the map's (id) order
    hits.sort_by_key(|h| std::cmp::Reverse(h.0));
    let total = hits.len();
    let offset = p.offset.unwrap_or(0).min(total);
    let limit = p.limit.unwrap_or(DEFAULT_LIMIT).clamp(1, MAX_LIMIT);
    let elements: Vec<Value> = hits.iter().skip(offset).take(limit).map(|(_, e)| (*e).clone()).collect();
    let mut out = json!({"total": total, "offset": offset, "returned": elements.len(), "elements": elements, "how": HOW});
    if total == 0 {
        out["hint"] = json!("nothing matched: try fewer or other words, a shorter prefix, or no panel / kind filter");
    } else if offset + limit < total {
        out["more"] = json!(format!("{} more: call again with offset {}", total - offset - limit, offset + limit));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ids(v: &Value) -> Vec<String> {
        v["elements"].as_array().unwrap().iter().map(|e| e["id"].as_str().unwrap().to_string()).collect()
    }

    fn find(p: UiMapParams) -> Value {
        search(&p).unwrap()
    }

    #[test]
    fn the_embedded_map_parses_and_every_entry_is_complete() {
        let m = map().unwrap();
        let els = m["elements"].as_array().unwrap();
        assert!(els.len() > 500, "{} entries", els.len());
        for e in els {
            let id = e["id"].as_str().unwrap();
            for k in ["label", "panel", "kind", "effect"] {
                assert!(e[k].is_string(), "{id} has no {k}");
            }
            assert!(e["reach"].as_array().is_some_and(|r| r.iter().all(Value::is_string)), "{id}: reach");
            assert!(e["command"].is_null() || e["command"].is_string(), "{id}: command");
        }
        // the panels and the menu bar are all there
        for p in ["Timeline", "Program", "Project", "Effects", "Header", "Export mode", "Menu: File", "Dialog: "] {
            assert!(els.iter().any(|e| e["panel"].as_str().unwrap().starts_with(p)), "nothing in {p}");
        }
    }

    #[test]
    fn prefix_panel_and_kind_filter() {
        let v = find(UiMapParams { prefix: Some("timeline.track.".into()), limit: Some(500), ..Default::default() });
        assert!(v["total"].as_u64().unwrap() > 3);
        assert!(ids(&v).iter().all(|i| i.starts_with("timeline.track.")), "{v}");
        let v = find(UiMapParams { panel: Some("export MODE".into()), limit: Some(500), ..Default::default() });
        assert!(v["total"].as_u64().unwrap() > 10);
        assert!(v["elements"].as_array().unwrap().iter().all(|e| e["panel"] == "Export mode"), "case-insensitive panel");
        let v = find(UiMapParams { kind: Some("tab".into()), limit: Some(500), ..Default::default() });
        assert!(v["total"].as_u64().unwrap() > 5);
        assert!(v["elements"].as_array().unwrap().iter().all(|e| e["kind"] == "tab"));
        let v = find(UiMapParams { panel: Some("Menu".into()), kind: Some("menu-item".into()), limit: Some(500), ..Default::default() });
        assert!(v["total"].as_u64().unwrap() > 200, "every menu command: {}", v["total"]);
    }

    #[test]
    fn a_query_finds_the_button_and_its_command() {
        // a menu command: its command is its id
        let v = find(UiMapParams { query: Some("add tracks".into()), ..Default::default() });
        let top = &v["elements"][0];
        assert_eq!(top["command"], "sequence.addTracks", "{v}");
        // a tool button: found by its label, with the command behind it
        let v = find(UiMapParams { query: Some("razor tool".into()), ..Default::default() });
        assert!(ids(&v).contains(&"tools.Razor".to_string()), "{v}");
        // an exact id ranks first
        let v = find(UiMapParams { query: Some("tools.Razor".into()), ..Default::default() });
        assert_eq!(v["elements"][0]["id"], "tools.Razor");
        // every word must match
        let v = find(UiMapParams { query: Some("razor zzzznotathing".into()), ..Default::default() });
        assert_eq!(v["total"], 0);
        assert!(v["hint"].is_string());
        assert!(v["how"].as_str().unwrap().contains("command_run"));
    }

    #[test]
    fn limit_and_offset_page_through_the_matches() {
        let all = find(UiMapParams { limit: Some(MAX_LIMIT), ..Default::default() });
        assert_eq!(all["returned"].as_u64(), Some(MAX_LIMIT as u64));
        let first = find(UiMapParams::default());
        assert_eq!(first["returned"].as_u64(), Some(DEFAULT_LIMIT as u64));
        assert!(first["more"].is_string());
        let second = find(UiMapParams { offset: Some(DEFAULT_LIMIT), ..Default::default() });
        assert_eq!(ids(&all)[DEFAULT_LIMIT..2 * DEFAULT_LIMIT], ids(&second)[..], "pages follow on");
        // hostile numbers are clamped, never a panic
        let v = find(UiMapParams { limit: Some(0), offset: Some(usize::MAX), ..Default::default() });
        assert_eq!(v["returned"], 0);
        let v = find(UiMapParams { limit: Some(usize::MAX), ..Default::default() });
        assert_eq!(v["returned"].as_u64(), Some(MAX_LIMIT as u64));
    }
}
